package repositorios

import classes.Categoria

object CategoriasRepo {
    // --- SAGAS ---
    val DB_SAGA = Categoria("DB Saga", 1)
    val SAIYAN_SAGA = Categoria("Saiyan Saga", 2)
    val PLANET_NAMEK_SAGA = Categoria("Planet Namek Saga", 3)
    val ANDROIDS_CELL_SAGA = Categoria("Androids/Cell Saga", 4)
    val MAJIN_BUU_SAGA = Categoria("Majin Buu Saga", 5)
    val FUTURE_SAGA = Categoria("Future Saga", 6)
    val UNIVERSE_SURVIVAL_SAGA = Categoria("Universe Survival Saga", 7)
    val SHADOW_DRAGON_SAGA = Categoria("Shadow Dragon Saga", 8)
    val DAIMA = Categoria("DAIMA", 9)

    // --- RAZAS Y FAMILIAS ---
    val PURE_SAIYANS = Categoria("Pure Saiyans", 10)
    val HYBRID_SAIYANS = Categoria("Hybrid Saiyans", 11)
    val EARTHLINGS = Categoria("Earthlings", 12)
    val NAMEKIANS = Categoria("Namekians", 13)
    val ANDROIDS = Categoria("Androids", 14)
    val ARTIFICIAL_LIFE_FORMS = Categoria("Artificial Life Forms", 15)
    val GOKUS_FAMILY = Categoria("Goku's Family", 16)
    val VEGETAS_FAMILY = Categoria("Vegeta's Family", 17)
    val WICKED_BLOODLINE = Categoria("Wicked Bloodline", 18)
    val YOUTH = Categoria("Youth", 19)
    val PEPPY_GALS = Categoria("Peppy Gals", 20)

    // --- TRANSFORMACIONES Y TÉCNICAS ---
    val SUPER_SAIYANS = Categoria("Super Saiyans", 21)
    val SUPER_SAIYAN_2 = Categoria("Super Saiyan 2", 22)
    val SUPER_SAIYAN_3 = Categoria("Super Saiyan 3", 23)
    val POWER_BEYOND_SUPER_SAIYAN = Categoria("Power Beyond Super Saiyan", 24)
    val FUSION = Categoria("Fusion", 25)
    val POTARA = Categoria("Potara", 26)
    val FUSED_FIGHTERS = Categoria("Fused Fighters", 27)
    val GIANT_FORM = Categoria("Giant Form", 28)
    val TRANSFORMATION_BOOST = Categoria("Transformation Boost", 29)
    val POWER_ABSORPTION = Categoria("Power Absorption", 30)
    val KAMEHAMEHA = Categoria("Kamehameha", 31)

    // --- ESTADOS Y PODERES  ---
    val REALM_OF_GODS = Categoria("Realm of Gods", 32)
    val FULL_POWER = Categoria("Full Power", 33)
    val GIANT_APE_POWER = Categoria("Giant Ape Power", 34)
    val MAJIN_POWER = Categoria("Majin Power", 35)
    val UNCONTROLLABLE_POWER = Categoria("Uncontrollable Power", 36)
    val POWERFUL_COMEBACK = Categoria("Powerful Comeback", 37)
    val POWER_OF_WISHES = Categoria("Power of Wishes", 38)
    val DEMONIC_POWER = Categoria("Demonic Power", 39)
    val MIRACULOUS_AWAKENING = Categoria("Miraculous Awakening", 40)
    val CORRODED_BODY_AND_MIND = Categoria("Corroded Body and Mind", 41)
    val RAPID_GROWTH = Categoria("Rapid Growth", 42)
    val MASTERED_EVOLUTION = Categoria("Mastered Evolution", 43)
    val TIME_LIMIT = Categoria("Time Limit", 44)
    val FINAL_TRUMP_CARD = Categoria("Final Trump Card", 45)

    // --- EQUIPOS Y GRUPOS ---
    val GINYU_FORCE = Categoria("Ginyu Force", 46)
    val TEAM_BARDOCK = Categoria("Team Bardock", 47)
    val UNIVERSE_6 = Categoria("Universe 6", 48)
    val REPRESENTATIVES_OF_UNIVERSE_7 = Categoria("Representatives of Universe 7", 49)
    val UNIVERSE_11 = Categoria("Universe 11", 50)
    val GT_HEROES = Categoria("GT Heroes", 51)
    val GT_BOSSES = Categoria("GT Bosses", 52)
    val SUPER_HEROES = Categoria("Super Heroes", 53)
    val SUPER_BOSSES = Categoria("Super Bosses", 54)
    val MOVIE_HEROES = Categoria("Movie Heroes", 55)
    val MOVIE_BOSSES = Categoria("Movie Bosses", 56)
    val TURTLE_SCHOOL = Categoria("Turtle School", 57)
    val WORLD_TOURNAMENT = Categoria("World Tournament", 58)
    val TOURNAMENT_PARTICIPANTS = Categoria("Tournament Participants", 59)

    // --- NUEVAS CATEGORÍAS ---
    val EARTH_BRED_FIGHTERS = Categoria("Earth-Bred Fighters", 60)
    val DEFENDERS_OF_JUSTICE = Categoria("Defenders of Justice", 61)
    val REVENGE = Categoria("Revenge", 62)
    val TARGET_GOKU = Categoria("Target: Goku", 63)
    val INHUMAN_DEEDS = Categoria("Inhuman Deeds", 64)
    val EXPLODING_RAGE = Categoria("Exploding Rage", 65)
    val CONNECTED_HOPE = Categoria("Connected Hope", 66)
    val ENTRUSTED_WILL = Categoria("Entrusted Will", 67)
    val ALL_OUT_STRUGGLE = Categoria("All-Out Struggle", 68)
    val BATTLE_OF_FATE = Categoria("Battle of Fate", 69)
    val ACCELERATED_BATTLE = Categoria("Accelerated Battle", 70)
    val BATTLE_OF_WITS = Categoria("Battle of Wits", 71)
    val CROSSOVER = Categoria("Crossover", 72)
    val DRAGON_BALL_HEROES = Categoria("Dragon Ball Heroes", 73)
    val SPECIAL_POSE = Categoria("Special Pose", 74)
    val WORTHY_RIVALS = Categoria("Worthy Rivals", 75)
    val SWORN_ENEMIES = Categoria("Sworn Enemies", 76)
    val BOND_OF_PARENT_AND_CHILD = Categoria("Bond of Parent and Child", 77)
    val SIBLINGS_BOND = Categoria("Siblings' Bond", 78)
    val BOND_OF_FRIENDSHIP = Categoria("Bond of Friendship", 79)
    val BOND_OF_MASTER_AND_DISCIPLE = Categoria("Bond of Master and Disciple", 80)
    val HEAVENLY_EVENTS = Categoria("Heavenly Events", 81)
    val WORLDWIDE_CHAOS = Categoria("Worldwide Chaos", 82)
    val OTHERWORLD_WARRIORS = Categoria("Otherworld Warriors", 83)
    val SAVIORS = Categoria("Saviors", 84)
    val JOINED_FORCES = Categoria("Joined Forces", 85)
    val LOW_CLASS_WARRIORS = Categoria("Low-Class Warriors", 86)
    val GIFTED_WARRIORS = Categoria("Gifted Warriors", 87)
    val SPACE_TRAVELING_WARRIORS = Categoria("Space-Traveling Warriors", 88)
    val TIME_TRAVELERS = Categoria("Time Travelers", 89)
    val DRAGON_BALL_SEEKERS = Categoria("Dragon Ball Seekers", 90)
    val SUCCESSORS = Categoria("Successors", 91)
    val STORIED_FIGURES = Categoria("Storied Figures", 92)
    val LEGENDARY_EXSISTENCE = Categoria("Legendary Existence", 93)
    val EARTH_PROTECTING_HEROES = Categoria("Earth-Protecting Heroes", 94)
    val MISSION_EXECUTION = Categoria("Mission Execution", 95)
    val TERRIFYING_CONQUERORS = Categoria("Terrifying Conquerors", 96)
    val PLANETARY_DESTRUCTION = Categoria("Planetary Destruction", 97)

}